spring:  
  config:
      activate:
         on-profile: dev
  devtools:
    add-properties: false
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8181
server:
  port: 8080
