spring:
   application.name: spring-session-with-redis
   security:
      oauth2:
         client:
            registration:
               github:
                  client-id: 0137e6e096b31141b615
                  client-secret: e1c4ec59c064fc8611df003ea6670ddc0ee21166
          