spring:  
  devtools:
    add-properties: false
  application:
    name: server-config
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: ${user.home}/workspace/0-projects/tuto-spring-cloud-config-repos
          clone-on-start: true
management:
  endpoint:
    refresh:
      enabled: true
server:
  port: 8181
